FROM golang:1.24-alpine

RUN apk update
RUN apk add jq npm

WORKDIR /app-dev

COPY go.mod go.sum .
RUN go mod download

WORKDIR /app-dev/app
COPY app/package.json .
RUN npm install

WORKDIR /app-dev
COPY . .

EXPOSE 8080
CMD ["go", "run", "./cmd/main.go"]

